name: Release

on:
  workflow_run:
    workflows: ['Main']
    branches: [main]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    name: Release
    permissions:
      contents: write # to create the release (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write # to create the pull request (changesets/action)
    uses: benhigham/.github/.github/workflows/release-changesets.yml@main
    with:
      node-version: 22
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
