name: Release

on:
  workflow_run:
    workflows: ['CI']
    branches: [main]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  setup:
    name: Setup environment
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: benhigham/.github/.github/workflows/setup-node.yml@main
    permissions:
      contents: read # to fetch code (actions/checkout)

  release:
    name: Release
    needs: setup
    permissions:
      contents: write # to create the release (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write # to create the pull request (changesets/action)
    uses: benhigham/.github/.github/workflows/release-changesets.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
